### ISSUE TITLE
EVC commits suicide if you attempt to delete empty row

### ISSUE THREAD

**Issue by saddleupandride** [Redon-Tech/Emergency-Vehicle-Creator#11]
to recreate;

Reset and confirm, it should generate an empty column
And then attempt to delete Row 1 even though its empty and then it dies
![image](https://user-images.githubusercontent.com/102647280/233763435-1c5698d0-6767-4ef6-8232-3e710f37b4c0.png)

**Comment by parker02311** [comment]
@saddleupandride could you possibly get a video of this happening with output enabled?

**Comment by saddleupandride** [comment]
@parker02311 this appears to be a one off, because now its not regenerating with an empty column, however I do have a screenshot from when it happened.
![image](https://user-images.githubusercontent.com/102647280/233763841-12d55c78-8b90-4dd7-80d1-d738ba9e8022.png)
![image](https://user-images.githubusercontent.com/102647280/233763847-9780ecc6-83c0-4a1e-9cbb-0776d7d700f7.png)

**Comment by parker02311** [comment]
Interesting, I will see if I can find any way to reproduce and fix it. Thanks for letting me know!

**Comment by saddleupandride** [comment]
yw!

**Comment by saddleupandride** [comment]
Figured out how to repro - open EVC to default, delete 1 or more rows and reset to make new pattern

**Comment by parker02311** [comment]
Fixed in 008c6634af7954672dd2059e7e54ed8089d9959c
