### ISSUE TITLE
blue rectangle thing remains after row deleted

### ISSUE THREAD

**Issue by saddleupandride** [Redon-Tech/Emergency-Vehicle-Creator#12]
![image](https://user-images.githubusercontent.com/102647280/233766857-b907d887-17f9-4afd-8306-928880abb630.png)

simply play, wait a second, pause, and delete row the blue highlight thing is paused on

**Comment by parker02311** [comment]
Known issue and should be fixed next update

**Comment by saddleupandride** [comment]
fast 💀
