### ISSUE TITLE
remove row button is a bit glitchy

### ISSUE THREAD

**Issue by saddleupandride** [Redon-Tech/Emergency-Vehicle-Creator#14]
its possible to click it multiple times and remove multiple rows, eg if you click it twice without realising you remove two rows as the popup will appear twice, hypothetically its possible to scale infinitely

not sure if its intentional or not 🤷

**Comment by parker02311** [comment]
No this is not intentional, we will look into fixing it.

**Comment by parker02311** [comment]
Fixed in 01ee0ee176ac0d9351604e12458ecf00e7a5522e
