### ISSUE TITLE
Tweens for Faders 

### ISSUE THREAD

**Issue by LidlDoner** [Redon-Tech/Emergency-Vehicle-Creator#16]
Ive recently been encountering the Tweens for Faders not working properly, and instead just instantly jumping between 0 and 1 (transparency). The one time I managed to get them to work properly, they promptly broke again upon transferring the pattern to another vehicle.

Output
![image](https://github.com/Redon-Tech/Emergency-Vehicle-Creator/assets/144060676/0c575362-f89e-45fc-a1bd-e16aca0a7ce3)
![image](https://github.com/Redon-Tech/Emergency-Vehicle-Creator/assets/144060676/013aa18e-0ab6-4719-a9c7-991bb8db199a)

Snapshot of Pattern
![image](https://github.com/Redon-Tech/Emergency-Vehicle-Creator/assets/144060676/38c1a996-d641-448a-8b59-62724177cc15)

Gif of Pattern not tweening correclty
https://gyazo.com/5950deead994b689d099a62a0c25abfe

**Comment by parker02311** [comment]
@LidlDoner if you could provide the vehicle to me over Discord so I can look into this, there is not nearly enough information provided for me to try to fix.

**Comment by parker02311** [comment]
Previous statement revoked...

**Comment by parker02311** [comment]
Fixed in a4c54356e6f92cbaef9fcc996266f037be4884f4
