### ISSUE TITLE
Pattern preview broken 

### ISSUE THREAD

**Issue by saddleupandride** [Redon-Tech/Emergency-Vehicle-Creator#17]
Not sure what caused it, helping a friend learn how to operate EVC (V2) when previews broke
![image](https://github.com/Redon-Tech/Emergency-Vehicle-Creator/assets/102647280/b4a5f30c-23c5-4220-a600-73b464bd49ad)
Appears every time user tries to play

**Comment by parker02311** [comment]
@saddleupandride do you have any videos of the issue happening

**Comment by saddleupandride** [comment]
No, however the names of the lights do disappear as intended, the blue
thing stays on the first row though the first row does not show at the top

**Comment by parker02311** [comment]
If you could get a video that would help a lot for debugging.

**Comment by saddleupandride** [comment]
it's happened to me twice now, same error but i'll see if i can get a video
of it next time

**Comment by parker02311** [comment]
@saddleupandride if you can not get a video it would also be helpful if you could just figure out a pattern to reproduce this so I can try debugging it.

**Comment by parker02311** [comment]
Closing this issue as I have been unable to reproduce this, if you could get a video of it happening or provide a easy way to reproduce I will look into fixing this again.
