### ISSUE TITLE
AG plugin attempts to incorrectly identify model

### ISSUE THREAD

**Issue by saddleupandride** [Redon-Tech/Emergency-Vehicle-Creator#18]
EVCPlugin_AG, line 126 is looking for a model;
`... or lightbarInstance:IsA("Model") == false...`
AG-Chassis utilises a `Folder` for ELS as per demo vehicles & documentation, resulting an error and EVC not functioning.
Changing line 126 results in ELS functioning as intended

**Comment by parker02311** [comment]
Will be fixed in the next update

**Comment by parker02311** [comment]
Fixed by 1e404bb
