### ISSUE TITLE
Overriding other sirens does not stop the other sirens properly

### ISSUE THREAD

**Issue by parker02311** [Redon-Tech/Emergency-Vehicle-Creator#21]
```lua
	if sirenData.overrideOtherSounds then
		if sirenData._type == "hold" then
			for _, v in pairs(soundPart:GetChildren()) do
				if v:IsA("Sound") and v ~= sound then
					if v:GetAttribute("OriginalVolume") == nil then
						v:SetAttribute("OriginalVolume", v.Volume)
					end
					v.Volume = 0
				end
			end
		else
			for _, v in pairs(soundPart:GetChildren()) do
				if v:IsA("Sound") and v ~= sound then
					v:Stop()
				end
			end
		end
	end
```

Should check if the siren is actually a siren and then use the `stopSiren` function

**Comment by MatthiasTHM** [comment]
![EVC Error](https://github.com/user-attachments/assets/3d5a9058-9f43-4532-938b-a3e9a721b69b)

A new error had appeared when I put this in.

**Comment by MatthiasTHM** [comment]
I added that in the EVC plugin script, but my override light pattern stays stuck when I switch to a different siren until I actually turn off the siren that does the override pattern.

**Comment by parker02311** [comment]
> I added that in the EVC plugin script, but my override light pattern stays stuck when I switch to a different siren until I actually turn off the siren that does the override pattern.

This code snippet is the bug, that is why.
